language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_aaecba9732b0_key -iv $encrypted_aaecba9732b0_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add deploy git@ssh.haver.chat:haver-server
- git push deploy
addons:
  ssh_known_hosts: ssh.haver.chat
